### ISSUE TITLE
Reboot Todo

### ISSUE THREAD

**Issue by amio** [amio/metalmonkey#17]
## Reboot Roadmap

- [x] `0.1` __DEV__ 搭起开发环境，基于 web extension api，支持 Firefox 和 Chrome
- [x] `0.2` __FEAT__ 几个基本页面样式引入 material-ui
- [x] `0.3` __FEAT__ 管理功能：安装脚本、移除脚本
- ~~`0.4` __FEAT__ popup：列出当前页的脚本、开启/禁用脚本~~
- [x] `0.5` __FEAT__ sync & cache
- [ ] `0.6` __FEAT__ 编辑器 & 创建脚本
- [ ] `0.7` __FEAT__ 支持 ESModule
- [ ] `0.9` __FEAT__ 兼容模式
- [ ] `0.10` __DEV__ 图片资源、编译和打包
- [ ] `1.0` 发布到 Chrome Web Store、Firefox Store
- [ ] `1.1` __SPEC__ Modern Userscript Spec
